import os

ENDPOINT_DOG_FACE_CROPPER = os.environ.get('ENDPOINT_DOG_FACE_CROPPER')
ENDPOINT_TENSORFLOW_MODEL = os.environ.get('ENDPOINT_TENSORFLOW_MODEL')

ENDPOINT_REPORTAR_MASCOTA = os.environ.get('ENDPOINT_REPORTAR_MASCOTA')
DB_URI = os.environ.get('MONGODB_URL')
DB_NAME = os.environ.get('DB_NAME')
DB_COLECCION = os.environ.get('DB_COLECCION')

ACCOUNT_NAME = 'mascotas'
ACCOUNT_KEY = '5ZQbfjqEz5xuHzP4XgKTiWMMyow6OdNlN7GNcx+k90PJLdgNZvaEYLEyLZqEvol8MLR6yXeo46SzM6fbwG4wyg=='
CONTAINER_NAME = '$web'